/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.cassandra.sidecar.routes.tokenrange;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Callable;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import com.google.common.collect.Range;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.extension.ExtendWith;

import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import net.bytebuddy.implementation.bind.annotation.SuperCall;
import org.apache.cassandra.distributed.api.IInstance;
import org.apache.cassandra.distributed.api.TokenSupplier;
import org.apache.cassandra.sidecar.testing.BootstrapBBUtils;
import org.apache.cassandra.sidecar.testing.TestTokenSupplier;
import org.apache.cassandra.testing.CassandraIntegrationTest;
import org.apache.cassandra.testing.ConfigurableCassandraTestContext;
import org.apache.cassandra.testing.IClusterExtension;

/**
 * Multi-DC Cluster expansion scenarios integration tests for token range replica mapping endpoint with the in-jvm
 * dtest framework.
 *
 * <p>Note: Some related test classes are broken down to have a single test case to parallelize test execution and
 * therefore limit the instance size required to run the tests from CircleCI as the in-jvm-dtests tests are memory bound
 */
@Tag("heavy")
@ExtendWith(VertxExtension.class)
class JoiningMultiDCTest extends JoiningBaseTest
{
    @CassandraIntegrationTest(
    nodesPerDc = 5, newNodesPerDc = 1, numDcs = 2, network = true, buildCluster = false)
    void retrieveMappingMultiDCJoiningTest(VertxTestContext context,
                                           ConfigurableCassandraTestContext cassandraTestContext)
    throws Exception
    {
        BBHelperDoubleClusterMultiDC.reset();
        // We'll manually swap around tokens, so use 0 as number of new DCs
        TestTokenSupplier tokenSupplier = TestTokenSupplier.evenlyDistributedTokens(6, 0, 2, 1);

        tokenSupplier.swap(5, 10);
        IClusterExtension<? extends IInstance> cluster = getMultiDCCluster(BBHelperDoubleClusterMultiDC::install, cassandraTestContext, tokenSupplier, null);

        runJoiningTestScenario(context,
                               BBHelperDoubleClusterMultiDC.transientStateStart,
                               BBHelperDoubleClusterMultiDC.transientStateEnd,
                               cluster,
                               generateExpectedRanges(tokenSupplier),
                               generateExpectedRangeDoubleClusterSizeMultiDC(tokenSupplier, sidecarTestContext.cassandraTestContext().annotation),
                               true,
                               tokenSupplier);
    }

    /**
     * Generates expected token range and replica mappings specific to the test case involving a 12 node cluster
     * across 2 DCs (5 initial nodes per DC) with 2 nodes joining the cluster (1 per DC), with RF 3 per DC
     * <p>
     * Expected ranges are generated by adding RF replicas per range in increasing order. The replica-sets in subsequent
     * ranges cascade with the next range excluding the first replica, and including the next replica from the nodes.
     * eg.
     * Range 1 - A, B, C
     * Range 2 - B, C, D
     * <p>
     * In a multi-DC scenario, a single range will have nodes from both DCs. The replicas are grouped by DC here
     * to allow per-DC validation as returned from the sidecar endpoint.
     * <p>
     * Ranges that include joining node replicas will have [RF + no. joining nodes in replica-set] replicas with
     * the joining nodes being added to the existing replica sets.
     * <p>
     * eg.
     * Range 1 - A, B, C
     * Range 2 - B, C, D (with D being the joining node)
     * Expected Range 2 - B, C, D, A (With A remaining as a replica during the join)
     * <p>
     */
    private Map<String, Map<Range<BigInteger>, List<String>>> generateExpectedRangeDoubleClusterSizeMultiDC(TokenSupplier tokenSupplier, CassandraIntegrationTest annotation)
    {

        List<Range<BigInteger>> expectedRanges = generateExpectedRanges(true, tokenSupplier, annotation);
        Map<Range<BigInteger>, List<String>> dc1Mapping = new HashMap<>();
        Map<Range<BigInteger>, List<String>> dc2Mapping = new HashMap<>();

        // Range 0: (-9223372036854775808, -6588122883467697007]
        dc1Mapping.put(expectedRanges.get(0), Arrays.asList("127.0.0.5", "127.0.0.3", "127.0.0.1"));
        dc2Mapping.put(expectedRanges.get(0), Arrays.asList("127.0.0.8", "127.0.0.2", "127.0.0.4"));

        // Range 1: (-6588122883467697007, -6588122883467697006]
        dc1Mapping.put(expectedRanges.get(1), Arrays.asList("127.0.0.5", "127.0.0.3", "127.0.0.11", "127.0.0.7"));
        dc2Mapping.put(expectedRanges.get(1), Arrays.asList("127.0.0.8", "127.0.0.2", "127.0.0.4"));

        // Range 2: (-6588122883467697006, -3952873730080618207]
        dc1Mapping.put(expectedRanges.get(2), Arrays.asList("127.0.0.5", "127.0.0.3", "127.0.0.11", "127.0.0.7"));
        dc2Mapping.put(expectedRanges.get(2), Arrays.asList("127.0.0.8", "127.0.0.4", "127.0.0.10"));

        // Range 3: (-3952873730080618207, -3952873730080618206] 
        dc1Mapping.put(expectedRanges.get(3), Arrays.asList("127.0.0.5", "127.0.0.9", "127.0.0.11", "127.0.0.7"));
        dc2Mapping.put(expectedRanges.get(3), Arrays.asList("127.0.0.8", "127.0.0.4", "127.0.0.10"));

        // Range 4: (-3952873730080618206, -1317624576693539407]
        dc1Mapping.put(expectedRanges.get(4), Arrays.asList("127.0.0.5", "127.0.0.9", "127.0.0.11", "127.0.0.7"));
        dc2Mapping.put(expectedRanges.get(4), Arrays.asList("127.0.0.8", "127.0.0.6", "127.0.0.10"));

        // Range 5: (-1317624576693539407, -1317624576693539406]
        dc1Mapping.put(expectedRanges.get(5), Arrays.asList("127.0.0.9", "127.0.0.11", "127.0.0.7", "127.0.0.1"));
        dc2Mapping.put(expectedRanges.get(5), Arrays.asList("127.0.0.8", "127.0.0.6", "127.0.0.10"));

        // Range 6: (-1317624576693539406, 1317624576693539393]
        dc1Mapping.put(expectedRanges.get(6), Arrays.asList("127.0.0.9", "127.0.0.7", "127.0.0.1"));
        dc2Mapping.put(expectedRanges.get(6), Arrays.asList("127.0.0.8", "127.0.0.6", "127.0.0.10"));

        // Range 7: (1317624576693539393, 1317624576693539394]
        dc1Mapping.put(expectedRanges.get(7), Arrays.asList("127.0.0.9", "127.0.0.3", "127.0.0.1"));
        dc2Mapping.put(expectedRanges.get(7), Arrays.asList("127.0.0.8", "127.0.0.6", "127.0.0.10"));

        // Range 8: (1317624576693539394, 3952873730080618193]
        dc1Mapping.put(expectedRanges.get(8), Arrays.asList("127.0.0.9", "127.0.0.3", "127.0.0.1"));
        dc2Mapping.put(expectedRanges.get(8), Arrays.asList("127.0.0.2", "127.0.0.6", "127.0.0.12", "127.0.0.10"));

        // Range 9: (3952873730080618193, 3952873730080618194]
        dc1Mapping.put(expectedRanges.get(9), Arrays.asList("127.0.0.5", "127.0.0.3", "127.0.0.1"));
        dc2Mapping.put(expectedRanges.get(9), Arrays.asList("127.0.0.2", "127.0.0.6", "127.0.0.12", "127.0.0.10"));

        // Range 10: (3952873730080618194, 6588122883467696993]
        dc1Mapping.put(expectedRanges.get(10), Arrays.asList("127.0.0.5", "127.0.0.3", "127.0.0.1"));
        dc2Mapping.put(expectedRanges.get(10), Arrays.asList("127.0.0.2", "127.0.0.6", "127.0.0.4", "127.0.0.12"));

        // Range 11: (6588122883467696993, 6588122883467696994]
        dc1Mapping.put(expectedRanges.get(11), Arrays.asList("127.0.0.5", "127.0.0.3", "127.0.0.1"));
        dc2Mapping.put(expectedRanges.get(11), Arrays.asList("127.0.0.8", "127.0.0.2", "127.0.0.4", "127.0.0.12"));

        // Range 12: (6588122883467696994, 9223372036854775807]
        dc1Mapping.put(expectedRanges.get(12), Arrays.asList("127.0.0.5", "127.0.0.3", "127.0.0.1"));
        dc2Mapping.put(expectedRanges.get(12), Arrays.asList("127.0.0.8", "127.0.0.2", "127.0.0.4"));

        return new HashMap<>()
        {
            {
                put("datacenter1", dc1Mapping);
                put("datacenter2", dc2Mapping);
            }
        };
    }

    /**
     * ByteBuddy helper for multiple joining nodes
     */
    public static class BBHelperDoubleClusterMultiDC
    {
        static CountDownLatch transientStateStart = new CountDownLatch(2);
        static CountDownLatch transientStateEnd = new CountDownLatch(2);

        public static void install(ClassLoader cl, Integer nodeNumber)
        {
            // We initially start a 10-node cluster (5 nodes per DC), and then want to add 2 more (1 per DC)
            // Therefore, install the interception of joining if the node number is > 10
            if (nodeNumber > 10)
            {
                BootstrapBBUtils.installFinishJoiningRingInterceptor(cl, BBHelperDoubleClusterMultiDC.class);
            }
        }

        @SuppressWarnings("unused")
        public static void finishJoiningRing(@SuperCall Callable<Void> orig) throws Exception
        {
            // trigger bootstrap start and wait until bootstrap is ready from test
            transientStateStart.countDown();
            awaitLatchOrTimeout(transientStateEnd, 2, TimeUnit.MINUTES, "transientStateEnd");
            orig.call();
        }

        @SuppressWarnings("unused")
        public static boolean bootstrap(@SuperCall Callable<Boolean> orig)
        {
            // trigger bootstrap start and wait until bootstrap is ready from test
            transientStateStart.countDown();
            awaitLatchOrTimeout(transientStateEnd, 2, TimeUnit.MINUTES, "transientStateEnd");
            // don't actually call the original which tries to commit, and fails because other nodes
            // are down and therefore the commit won't complete
            return false;
        }

        public static void reset()
        {
            transientStateStart = new CountDownLatch(2);
            transientStateEnd = new CountDownLatch(2);
        }
    }
}
