/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.cassandra.sidecar.routes.tokenrange;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Callable;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import com.google.common.collect.Range;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.extension.ExtendWith;

import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import net.bytebuddy.implementation.bind.annotation.SuperCall;
import org.apache.cassandra.distributed.api.IInstance;
import org.apache.cassandra.distributed.api.TokenSupplier;
import org.apache.cassandra.sidecar.testing.BootstrapBBUtils;
import org.apache.cassandra.sidecar.testing.TestTokenSupplier;
import org.apache.cassandra.testing.CassandraIntegrationTest;
import org.apache.cassandra.testing.ConfigurableCassandraTestContext;
import org.apache.cassandra.testing.IClusterExtension;

/**
 * Multi-DC Cluster expansion scenarios integration tests for token range replica mapping endpoint with the in-jvm
 * dtest framework.
 * <p>
 * Note: Some related test classes are broken down to have a single test case to parallelize test execution and
 * therefore limit the instance size required to run the tests from CircleCI as the in-jvm-dtests tests are memory bound
 */
@Tag("heavy")
@ExtendWith(VertxExtension.class)
public class MultiDCSingleReplicatedJoiningTest extends JoiningBaseTest
{
    @CassandraIntegrationTest(
    nodesPerDc = 5, newNodesPerDc = 1, numDcs = 2, network = true, buildCluster = false)
    void retrieveMappingsSingleDCReplicatedKeyspace(VertxTestContext context,
                                                    ConfigurableCassandraTestContext cassandraTestContext)
    throws Exception
    {
        BBHelperMultiDC.reset();
        // We'll manually swap around tokens, so use 0 as number of new DCs
        TestTokenSupplier tokenSupplier = TestTokenSupplier.evenlyDistributedTokens(6, 0, 2, 1);
        tokenSupplier.swap(5, 10);
        IClusterExtension<? extends IInstance> cluster = getMultiDCCluster(BBHelperMultiDC::install, cassandraTestContext, tokenSupplier,
                                                                           builder -> builder.additionalInstanceConfig(Map.of("progress_barrier_default_consistency_level", "QUORUM",
                                                                                                                              "progress_barrier_timeout", "30s",
                                                                                                                              "cms_await_timeout", "60s",
                                                                                                                              "accord.enabled", "false",
                                                                                                                              "write_request_timeout", "10s")));
        CassandraIntegrationTest annotation = sidecarTestContext.cassandraTestContext().annotation;
        runJoiningTestScenario(context,
                               BBHelperMultiDC.transientStateStart,
                               BBHelperMultiDC.transientStateEnd,
                               cluster,
                               generateExpectedRanges(false, tokenSupplier, annotation),
                               generateExpectedRangeMappingOneOf2DCs(tokenSupplier, annotation),
                               false,
                               tokenSupplier);
    }

    /**
     * Generates expected token range and replica mappings specific to the test case involving a 5 node cluster
     * with the additional node joining the cluster
     * <p>
     * Expected ranges are generated by adding RF replicas per range in increasing order. The replica-sets in subsequent
     * ranges cascade with the next range excluding the first replica, and including the next replica from the nodes.
     * eg.
     * Range 1 - A, B, C
     * Range 2 - B, C, D
     * <p>
     * Ranges that include the joining node will have [RF + no. joining nodes in replica-set] replicas with
     * the replicas being the existing nodes in ring-order.
     * eg.
     * Range 1 - A, B, C
     * Range 2 - B, C, D (with E being the joining node)
     * Expected Range 2 - B, C, D, E
     */
    private Map<String, Map<Range<BigInteger>, List<String>>> generateExpectedRangeMappingOneOf2DCs(TokenSupplier tokenSupplier, CassandraIntegrationTest annotation)
    {
        List<Range<BigInteger>> expectedRanges = generateExpectedRanges(false, tokenSupplier, annotation);
        Map<Range<BigInteger>, List<String>> dc1Mapping = new HashMap<>();

        // Range 1
        dc1Mapping.put(expectedRanges.get(0), Arrays.asList("127.0.0.5", "127.0.0.1", "127.0.0.3"));

        // Range 2 (write survey range)
        dc1Mapping.put(expectedRanges.get(1), Arrays.asList("127.0.0.5", "127.0.0.7", "127.0.0.11", "127.0.0.3"));

        // Range 3
        dc1Mapping.put(expectedRanges.get(2), Arrays.asList("127.0.0.5", "127.0.0.7", "127.0.0.11", "127.0.0.3"));

        // Range 4 (write survey range)
        dc1Mapping.put(expectedRanges.get(3), Arrays.asList("127.0.0.5", "127.0.0.7", "127.0.0.9", "127.0.0.11"));

        // Range 5
        dc1Mapping.put(expectedRanges.get(4), Arrays.asList("127.0.0.5", "127.0.0.7", "127.0.0.9", "127.0.0.11"));

        // Range 6 (write survey range)
        dc1Mapping.put(expectedRanges.get(5), Arrays.asList("127.0.0.7", "127.0.0.9", "127.0.0.11", "127.0.0.1"));

        // Range 7
        dc1Mapping.put(expectedRanges.get(6), Arrays.asList("127.0.0.7", "127.0.0.9", "127.0.0.1"));

        // Range 8 (write survey range)
        dc1Mapping.put(expectedRanges.get(7), Arrays.asList("127.0.0.9", "127.0.0.1", "127.0.0.3"));

        // Range 9
        dc1Mapping.put(expectedRanges.get(8), Arrays.asList("127.0.0.9", "127.0.0.1", "127.0.0.3"));

        // Range 10 (write survey range)
        dc1Mapping.put(expectedRanges.get(9), Arrays.asList("127.0.0.5", "127.0.0.1", "127.0.0.3"));

        // Range 11
        dc1Mapping.put(expectedRanges.get(10), Arrays.asList("127.0.0.5", "127.0.0.1", "127.0.0.3"));

        // Range 12
        dc1Mapping.put(expectedRanges.get(11), Arrays.asList("127.0.0.5", "127.0.0.1", "127.0.0.3"));

        return Map.of("datacenter1", dc1Mapping);
    }

    /**
     * ByteBuddy helper for multiple joining nodes
     */
    public static class BBHelperMultiDC
    {
        static CountDownLatch transientStateStart = new CountDownLatch(2);
        static CountDownLatch transientStateEnd = new CountDownLatch(2);

        public static void install(ClassLoader cl, Integer nodeNumber)
        {
            // Test case involves adding 2 nodes to a 10 node cluster (5 per DC)
            // We intercept the bootstrap of nodes (11,12) to validate token ranges
            if (nodeNumber > 10)
            {
                BootstrapBBUtils.installFinishJoiningRingInterceptor(cl, BBHelperMultiDC.class);
            }
        }

        @SuppressWarnings("unused")
        public static void finishJoiningRing(boolean didBootstrap, Collection<?> tokens, @SuperCall Callable<Void> orig) throws Exception
        {
            // trigger bootstrap start and wait until bootstrap is ready from test
            transientStateStart.countDown();
            awaitLatchOrTimeout(transientStateEnd, 2, TimeUnit.MINUTES, "transientStateEnd");
            orig.call();
        }

        @SuppressWarnings("unused")
        public static boolean bootstrap(@SuperCall Callable<Boolean> orig)
        {
            // trigger bootstrap start and wait until bootstrap is ready from test
            transientStateStart.countDown();
            awaitLatchOrTimeout(transientStateEnd, 4, TimeUnit.MINUTES, "transientStateEnd");
            // don't actually call the original which tries to commit, and fails because other nodes
            // are down and therefore the commit won't complete
            return false;
        }

        public static void reset()
        {
            transientStateStart = new CountDownLatch(2);
            transientStateEnd = new CountDownLatch(2);
        }
    }
}
